export default {
  GET_MOVIES_LOADING: "GET_MOVIES_LOADING",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",

  GET_MOVIE_DETAILS_AND_NAVIGATE_LOADING:
    "GET_MOVIE_DETAILS_AND_NAVIGATE_LOADING",
  GET_MOVIE_DETAILS_AND_NAVIGATE_SUCCESS:
    "GET_MOVIE_DETAILS_AND_NAVIGATE_SUCCESS",
  GET_MOVIE_DETAILS_AND_NAVIGATE_ERROR: "GET_MOVIE_DETAILS_AND_NAVIGATE_ERROR",
};
