export default {
  GET_MOVIES_LOADING: "GET_MOVIES_LOADING",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",

  GET_MOVIE_DETAILS_AND_NAVIGATE_LOADING:
    "GET_MOVIE_DETAILS_AND_NAVIGATE_LOADING",
  GET_MOVIE_DETAILS_AND_NAVIGATE_SUCCESS:
    "GET_MOVIE_DETAILS_AND_NAVIGATE_SUCCESS",
  GET_MOVIE_DETAILS_AND_NAVIGATE_ERROR: "GET_MOVIE_DETAILS_AND_NAVIGATE_ERROR",

  SEARCH_MOVIES_LOADING: "SEARCH_MOVIES_LOADING",
  SEARCH_MOVIES_SUCCESS: "SEARCH_MOVIES_SUCCESS",
  SEARCH_MOVIES_ERROR: "SEARCH_MOVIES_ERROR",

  SEARCH_TEXT_CHANGE: "SEARCH_TEXT_CHANGE",
};
